language: node_js

node_js:
  - '10'

notifications:
  email:
    - hello@therichart.space

before_deploy:
  - yarn build

deploy:
  - provider: netlify
    project: public/
    skip_cleanup: true
    site: therichard.space
    prod: true # Deploying to production server
    on: master  
    edge: true # Using v2 prerelease build tools



cache:
  yarn: true
  directories:
    - node_modules

