language: node_js

node_js:
  - '8'


notifications:
  email:
    - richardvanthof@pm.me

before_deploy:
  - yarn lint
  - yarn build

deploy:
  provider: surge
  project: public
  skip_cleanup: true
  domain: therichartspace.surge.sh
  on: master

cache:
  yarn: true
  directories:
    - node_modules

