language: node_js

node_js:
  - '10'

notifications:
  email:
    - hello@therichart.space

before_deploy:
  - yarn build

deploy:
  provider: netlify
  project: public/
  skip_cleanup: true
  domain: elegant-goodall-ebb0b7.netlify.com
  edge: true # Using v2 prerelease build tools
  prod: true # Deploying to production server
  on: master


cache:
  yarn: true
  directories:
    - node_modules

