language: node_js

node_js:
  - '10'

notifications:
  email:
    - hello@therichart.space

before_deploy:
  - yarn build

deploy:
  provider: netlify
  message: deploying to Netlify...
  site: therichardspace
  dir: public/
  prod: true
  edge: true # opt in to dpl v2
  on: master 

cache:
  yarn: true
  directories:
    - node_modules

