language: node_js

node_js:
  - '10'

notifications:
  email:
    - hello@therichard.space

before_deploy:
  - yarn lint
  - yarn builds

deploy:
  provider: netlify
  message: deploying to Netlify...
  site: 470989a8-7889-4012-8175-5a3d601a9a6d
  dir: public/
  edge: true # opt in to dpl v2
  prod: true

cache:
  yarn: true
  directories:
    - node_modules

